# 先创建网络组
# docker版本建议18.0以上
# docker network create go_network
version: '3'
services:
  compose_mysql:
    image: mysql:5.7
    container_name: compose_mysql
    ports:
    - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go-gin-starter
    volumes:
      - /opt/docker/mysql_test/data:/var/lib/mysql           # 挂载数据目录
      - /opt/docker/mysql_test/config:/etc/mysql/conf.d      # 挂载配置文件目录
  compose_redis:
    image: redis:latest
    container_name: compose_redis
    ports:
    - 6381:6379
    volumes:
      - /opt/docker/redis_test/conf:/usr/local/etc/redis
      - /opt/docker/redis_test/data:/data
    command:
      redis-server
  go-gin-server_test:
    build: ./
    image: compose_go-server:v1
    ports:
      - 80:8000
    container_name: go-gin-server_test

networks:
  default:
    external:
      name: go_network